version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: "mongodb+srv://masingamasibonge:R75JCPExhhcyyr81@cluster0.ns1yp.mongodb.net/myFirstDatabase"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
